### ISSUE TITLE
Optimize bitmap output for ssd1306

### ISSUE THREAD

**Issue by koriwi** [koriwi/freedeck-configurator#1]
As suggested by @bitbank2:
the arduino needs to write 8x8 blocks of pixels to the ssd1306 controller but the configurator spits out the bitmaps in the default format. To remove the need to convert the row by row pixels to 8x8 blocks, we need to do it in the configurator when exporting the config file.

**Comment by bitbank2** [comment]
The OLED memory is laid out in 1 byte columns (8 pixels, LSB on top). The Arduino can write any number of 1 byte columns of 8 pixels at a time.

**Comment by koriwi** [comment]
@bitbank2 i linked my pr. this works and is much faster than before.
the configurator does not yet have the ability to reverse the optimization when loading the config files for reediting them

**Comment by koriwi** [comment]
@bitbank2 giving up for today/tonight. tried the whole day to wrap my head around understanding whats happening in your bitmap conversion with all the bitwise operators etc and how to revert it. but for now no chance. will try on sunday.
