### ISSUE TITLE
Allow changing of text position

### ISSUE THREAD

**Issue by vrocco** [koriwi/freedeck-configurator#13]
Text appears to only go to the right of the icon. Would be nice if you could put text above or below and icon would scale according to text size to fit the display space.

**Comment by koriwi** [comment]
Text position is not yet ready. but icon size is done here http://fdbeta.gosewis.ch/
but old config file is not (yet) compatible

**Comment by koriwi** [comment]
icon size is live on https://freedeck.gosewis.ch
the feature was only requested once, to put the text below.
i thinks its a worse idea to put the text below, because we have more x-axis pixels than y-axis pixels.
please reopen this ticket if you have a nice example (just do it in paint for example)
