### ISSUE TITLE
Allow editing of default "back a page" icon

### ISSUE THREAD

**Issue by vrocco** [koriwi/freedeck-configurator#14]
Configurator automatically generates the "go back a page" icon but you can't invert or change dithering. As a result, it looks like it has a bunch of tiny pinholes on my display (needs dithering toggled).

**Comment by koriwi** [comment]
try this beta. should work for you now.
click on settings in the top right corner :)
(you can make any display back display opening the display and then right click the preview)
http://fdbeta.gosewis.ch/ (the new configurator is not yet compatible with the old config files)
please reopen the ticket if you still have issues
