### ISSUE TITLE
Issue with generating long press configuration

### ISSUE THREAD

**Issue by Maxlem1337** [koriwi/freedeck-configurator#15]
Create a new config on: http://freedeck.gosewis.ch
- Add New Page
- Configure a key as follows: 
- - ![image](https://user-images.githubusercontent.com/24243550/88864506-a8fc5500-d205-11ea-8e61-98ec84a1bda6.png)
- Save Config 
- - Longpress does not work with this config
- Load the config you just created
- Save Config
- When comparing the 2 config files, you can see the difference at address 0x10
![image](https://user-images.githubusercontent.com/24243550/88864927-b5cd7880-d206-11ea-8d1e-e5eacbcc2c39.png)

**Comment by koriwi** [comment]
@Maxlem1337 is this still relevant?

**Comment by koriwi** [comment]
@Maxlem1337 http://fdbeta.gosewis.ch/
please try this new version. should work now
