### ISSUE TITLE
Change icon when button is pressed

### ISSUE THREAD

**Issue by MattiaEffendi** [koriwi/freedeck-configurator#31]
Hi!
Would it be possible to add the possibility of change the icon when a button is pressed?

e.g. Mute microphone button -> when i click, i want to see a microphone icon with a cross on top of it, and when i re-press it the cross should go away, in order to see if the microphone is muted right away.

Thanks!

**Comment by koriwi** [comment]
it is possible but not very usefull. imagine you pressed it on the freedeck to mute. so the icon is now with a cross.
But now you unmute by clicking in the software and not on the freedeck. the freedeck still show the cross but its not muted anymore.

**Comment by koriwi** [comment]
feel free to reopen the issue if you have an idea to solve this problem
