### ISSUE TITLE
On rescaling the freedeck (from 3x2 to something else) the preview is acting wrong

### ISSUE THREAD

**Issue by legomannetje** [koriwi/freedeck-configurator#33]
I wanted to upgrade one of my exsisting configs from the 3x2 size freedeck to the 5x3 format. When i loaded it, and changed the screensize in the settings the screens did resize to the correct size, but no new screens appeared. 

The otherway arround, if you go from 3x2 to 1x2 the screens dont disappear, and you get a long line.

![FreedeckIssue](https://user-images.githubusercontent.com/11525684/115360584-097e5880-a1c0-11eb-95f5-80e7cb80e505.PNG)

![FreedeckIssue1](https://user-images.githubusercontent.com/11525684/115360681-231fa000-a1c0-11eb-8d4d-c54e5505c4d3.PNG)

To recreate this issue. Load an 3x2 config, and resize it.

Information:
FreeDeck Configurator
Version: 1.5.0
Build: 1618600750395
Commit: ea03bf0

**Comment by koriwi** [comment]
Yeah. This is known and is listed in the known issues at the bottom if the readme

**Comment by koriwi** [comment]
fixed in dev
