### ISSUE TITLE
allow changing the page layout

### ISSUE THREAD

**Issue by koriwi** [koriwi/freedeck-configurator#4]
right now the configurator only uses a 3x2 layout of the prototype.
the width and height need to be exposed to the user

**Comment by ryanaukes** [comment]
Hi, 

First of all, thanks for sharing all these files!
I am planning to make a custom 5x3 version of the Freedeck.
I am wondering if this feature (changing the page layout) will be available soon?

Thanks in advance!

**Comment by koriwi** [comment]
i cant promise anything. but its not that hard. if you know react, you can try to make a pull request

**Comment by ryanaukes** [comment]
Thanks for your reply! Unfortunately I don't know react.
I was looking for the code, but I did not really understand it.
My parts are still on their way, so I don't need it right now, but It would be awesome if this could be added.
Are there any other ways to configure the FreeDeck without using the configurator?

**Comment by ryanaukes** [comment]
All my parts finally arrived. Is there a way to configure the FreeDeck without using the configurator? By using the configurator I am limited to a 3x2 layout, while my hardware is 5x3. Thank!

**Comment by legomannetje** [comment]
This is implemented in V1.5 of the configurator and can be closed @koriwi
