### ISSUE TITLE
Copy/Paste a button from one "screen" of configured buttons to another

### ISSUE THREAD

**Issue by TakGalaman** [koriwi/freedeck-configurator#44]
It's cool you can click and drag one button to another place. I'd like to be able to, for example, hold shift when starting the click and drag and if I do that then leave behind the button I'm copying from and still allow me to configure another button the same way.

**Comment by koriwi** [comment]
sounds nice. if i remember, i will do it ;)

**Comment by koriwi** [comment]
It's done! Just hold ctrl. Instead of switching it will copy now :)
